### ISSUE TITLE
Full support for applying z_developer_showupdate to non anv_mapfixes entities

### ISSUE THREAD

**Issue by Derpduck** [Tsuey/L4D2-Community-Update#1]
As defined by https://github.com/Tsuey/L4D2-Community-Update/blob/master/scripts/vscripts/z_developer_showupdate.nut#L363 any entity not prefixed with anv_mapfixes will not be displayed with the same amount of information as those from the Last Stand update.

This includes lump and _commentary.txt entities as mentioned in the comment, but can also be extended to entities added through Stripper:Source. This can be circumvented by appending `anv_mapfixes` to the targetname, but this isn't an ideal way of doing this. For working with Stripper this feature is hugely beneficial, especially when comparing with existing clips or working with angled blockers. [Here's an example of me using the described method](https://imgur.com/a/zbTNEd1), where before viewing these clips in-game at all wouldn't have been possible.

Perhaps adding a check for values of `mapupdate` could simply be used to separate the viewing of these differently grouped entities, allowing ShowUpdate to specify viewing all groups at once or only a specific group. I believe the commentary blockers all include "mapupdate" "1" in their parameters already.

**Comment by Tsuey** [comment]
Derpduck closed this issue because ShowUpdate() will be reworked and extended.

Original user experience will remain unchanged.
