### ISSUE TITLE
Navigation Mesh Attribute Question

### ISSUE THREAD

**Issue by Vitamin4107** [Tsuey/L4D2-Community-Update#100]
What made Terror/Base (unknown) Navigation Mesh Attribute = 8
On [ValveDeveloper](https://developer.valvesoftware.com/wiki/List_of_L4D_Series_Nav_Mesh_Attributes) this flag (8) doesn't exists

If try spawn this flag via Entity func_nav_attribute_region area colored to blue color (as NOT_CLEARABLE flag)
<a href="https://ibb.co/Wgv9wsM"><img src="https://i.ibb.co/ChKdZWY/1.png" alt="1" border="0"></a>
<a href="https://ibb.co/d4G8rQW"><img src="https://i.ibb.co/8g610jK/2.jpg" alt="2" border="0"></a>

So. What made this Terror/Base Nav Attribute number 8 ?

**Comment by Nesciuse** [comment]
Spawn attributes 1,2 and 8 are unused. They have same color as NOT_CLEARABLE for some reason. Not sure what exactly you are asking about it.
