### ISSUE TITLE
c3m3_shantytown - [survivor Bot AI Nav Issue]

### ISSUE THREAD

**Issue by CootieDwagon** [Tsuey/L4D2-Community-Update#123]
when an ALL AI survivor bot team plays on this map c3m3_shantytown when they get close to the panic event, they simply bypass the panic event entirely (even if you have an up to date plugin or mod that lets them trigger the panic event they still bypass it)

they bypass the event by going through here:
https://steamcommunity.com/sharedfiles/filedetails/?id=2636695197

and through here:
https://steamcommunity.com/sharedfiles/filedetails/?id=2636695281

i would also assume that the AI survivor bots would also do the same when using the old "jump over the rock to skip panic event" shortcut that was patched out

**Comment by Nesciuse** [comment]
Give this a try with the newest commit. Should be working correctly now

**Comment by alexiscoutinho** [comment]
Namely #160.

**Comment by alexiscoutinho** [comment]
Just verified. Indeed fixed. Can be closed.
