### ISSUE TITLE
sound issues

### ISSUE THREAD

**Issue by FighterJet16** [Tsuey/L4D2-Community-Update#134]
So basically i have issues where all music goes silent and survivor dialogue stops and I can only hear gunshots and delayed shove sounds this happens on custom workshop maps and official maps.

**Comment by shqke** [comment]
You may have insufficient resources, or issues with hardware.

Verify your game cache, disable all workshop addons, and see if issue persists.

**Comment by FighterJet16** [comment]
alright will do
