### ISSUE TITLE
Survivors can hang on unreachable places ?

### ISSUE THREAD

**Issue by lunatixxx** [Tsuey/L4D2-Community-Update#139]
Obviously the situation is very improbable and Zoey will probably have die from the fall anyway, but they should not be able to hang on these ledges.

https://www.youtube.com/watch?v=ZLU9O0YnAQs

**Comment by alexiscoutinho** [comment]
Related to #49.

**Comment by A1mDev** [comment]
Yes, the same is with spitter, other grenades and a jockey, if he jumps under his feet, it will be the same.
