### ISSUE TITLE
[FR] Mute other people voice chat

### ISSUE THREAD

**Issue by FurtadoPires** [Tsuey/L4D2-Community-Update#148]
Would be possible to implement an option to mute the voice chat of another player without voting? It's usually a problem when you're playing versus and can't properly hear the specials because some beginner is breathing using open mic (and they never realize it).

Other source games like TF2 already have this option, so I wonder if this could be possible for l4d too.

**Comment by A1mDev** [comment]
@FurtadoPires, voice_show_mute, voice_mute console commands.

**Comment by shqke** [comment]
Duplicate #142.
