### ISSUE TITLE
Isn't "survivor_max_incapacitated_count" 0 redundant in Death's Door?

### ISSUE THREAD

**Issue by alexiscoutinho** [Tsuey/L4D2-Community-Update#150]
If the mutation already has `SurvivorMaxIncapacitatedCount = 0` as vscript, which has priority, what's the point of setting it as a convar in gamemodes.txt?

**Comment by shqke** [comment]
Sounds like a nit picking at this point, don't you think?

**Comment by alexiscoutinho** [comment]
May be, but it's not like there is a high amount of activity or time allocation/management lately. I thought about making a PR right away, but I wasn't sure it would be acceptable (the question...). Judging from your response, the answer seems like yes. Furthermore, there could have been the possibility that not setting the convar could cause a rare error/bug, or that the convar would act as a minimal fallback in case the script failed, or to simply be more intuitive (what's going on...) to people who are not aware of the vscript layer. In the latter two, however, the follow-up action would be to add other submissive convars like `director_convert_pills 0`.

**Comment by Tsuey** [comment]
> May be, but it's not like there is a high amount of activity or time allocation/management lately. I thought about making a PR right away, but I wasn't sure it would be acceptable

Generally whatever someone wants to take on, they are free to do so. We all just need to keep in mind that not everything may be accepted. There's no guarantees that Valve will accept the commits to this repo, all we know is that it's possible and probable, but we don't have any dates. This [Steam thread](https://steamcommunity.com/app/550/discussions/0/3083268548812820489/) is sometimes more active, just slow for the holidays.

Don't let us stand in your way.
