### ISSUE TITLE
Inaccessible spot for spawned items c1m3_mall

### ISSUE THREAD

**Issue by Hawkins93** [Tsuey/L4D2-Community-Update#182]
Near the starting safe room.
Impossible to pick the item, even with double jump. Tried from all sides.

![image](https://user-images.githubusercontent.com/2848519/161795468-c94b7505-240d-4562-977c-f3e1a440d87a.png)
![image](https://user-images.githubusercontent.com/2848519/161795514-1d66c76d-e27b-415f-ad8a-ea6022954bad.png)

**Comment by shqke** [comment]
Please attach and embed images instead of using external sources. 👍
