### ISSUE TITLE
Inaccessible spot for spawned items c1m2_streets

### ISSUE THREAD

**Issue by Hawkins93** [Tsuey/L4D2-Community-Update#183]
This one appears to be inside the wall

![image](https://user-images.githubusercontent.com/2848519/161795704-3764a4e5-67ac-403a-b026-6061cf53a621.png)
Edit: Here from another view:
![image](https://user-images.githubusercontent.com/2848519/161795736-099c9b1f-df9a-45af-8562-99b88df9abc8.png)

**Comment by Hawkins93** [comment]
> Does it still happens if you disable your mods?

It should. I have no plugins or mods that alter spawning behavior or spots of items.

**Comment by Nesciuse** [comment]
This one is fixed in one of the commits with c1m2 lumps. Can be closed
