### ISSUE TITLE
The motel roof is locked again on c2m1_highway

### ISSUE THREAD

**Issue by accelerator74** [Tsuey/L4D2-Community-Update#184]
![20220409074248_1](https://user-images.githubusercontent.com/18032476/162556736-186e244b-39e1-4e04-9823-61c64cf2ce41.jpg)
This happened after applying the pull request https://github.com/Tsuey/L4D2-Community-Update/pull/131
This has been removed:
```php
kill_entity( Entities.FindByClassnameNearest( "env_player_blocker", Vector( 1388, 5660, -649 ), 1 ) );
kill_entity( Entities.FindByClassnameNearest( "env_player_blocker", Vector( 2972, 3724, -649 ), 1 ) );
```

**Comment by Derpduck** [comment]
The 2 blockers are removed from the commentary.txt files in the same PR:
https://github.com/Tsuey/L4D2-Community-Update/pull/131/commits/44a95623460c5bbb880c2b54f42f8a6feee02719#diff-d80e061a49fe0d6f41858595a59a569038fd6f2f91b1161b79c5843bf17aaf9fL19

Once these files are updated in the live game they will no longer spawn, if you are using these changes in a custom server in the meantime the commentary.txt files will only be loaded when packaged in a vpk.
