### ISSUE TITLE
Inaccessible Item spawn on No Mercy, c8m3_sewers

### ISSUE THREAD

**Issue by Hawkins93** [Tsuey/L4D2-Community-Update#186]
Since i couldn't find this in open/closed issues i decided to report it.
![image](https://user-images.githubusercontent.com/98384553/162592606-e533c2c3-06a7-42d4-ae6b-61c9effc010c.png)
![image](https://user-images.githubusercontent.com/98384553/162592656-95614204-b8fc-49da-b448-05217c95d29c.png)
![image](https://user-images.githubusercontent.com/98384553/162592678-4fcdb129-0b70-484d-aab5-e03e4299581b.png)

**Comment by Nesciuse** [comment]
Already fixed in comitted lmp

**Comment by Hawkins93** [comment]
@alexiscoutinho Hi, thanks for the info. I will likely install it after finishing debugging some issues on my servers.
