### ISSUE TITLE
c2m4 food cart ladder

### ISSUE THREAD

**Issue by Derpduck** [Tsuey/L4D2-Community-Update#2]
https://github.com/Tsuey/L4D2-Community-Update/blob/master/scripts/vscripts/anv_versus.nut#L577

The ladder on the food cart in front of the saferoom is cloned from this ladder:
![](https://i.imgur.com/UzUvguM.png)

Where Valve accidently included the clipping around the ladder as a part of it, which causes the ladder to extend further than it is supposed to and block players behind the food cart.

![](https://i.imgur.com/bN4xzHO.jpeg)
![](https://i.imgur.com/M0W3uDi.jpeg)

It also means that players climbing up the ladder from the angled parts will generally fall off before reaching the top.

**Comment by Tsuey** [comment]
Will be replaced with a different ladder in the next commit!
