### ISSUE TITLE
c12m5_cornfield clip issue

### ISSUE THREAD

**Issue by Mysterious-Pootis** [Tsuey/L4D2-Community-Update#211]
![20220428190113_1](https://user-images.githubusercontent.com/104587389/165807007-87172808-c5ee-4eab-b8f5-d3da47b9b661.jpg)
This clip is an **Infected** clip which makes this spot a god spot. Please either change it to **All** or **Survivor** clip. Or get rid of it entirely.

**Comment by FurtadoPires** [comment]
Related to #75
