### ISSUE TITLE
Add Hazmat Infected to Liberty Mall

### ISSUE THREAD

**Issue by True-Boredom** [Tsuey/L4D2-Community-Update#236]
# Add Hazmat Infected to Liberty Mall

I believe that the z_population of c1m3 and c1m4 should be changed to "c1streets", the same population used by c1m1 and c1m2, so that the entirety of Dead Center will use this population and allow hazmat zombies to spawn.

Pros:
1. Lore consistency. It honestly has never made sense that you spend the first two maps of the campaign traveling from one ceda evac site to another, and when you finally get to the mall there are no ceda agents to be found.
2. These maps will be slightly harder in versus mode, (which is good, in my opinion), because most survivor teams can steamroll these levels pretty easily. (Reminder that hazmat zombies do not drop bilejars in versus mode) Actually, at only a 5% spawn rate, the hazmat infected would probably not impact balance for versus in any visible way.

Cons:
None that don't already apply to No Mercy or The Sacrifice, which spawn hazmat infected in far greater numbers than the measly 5% spawn rate that I'm proposing. If the hazmat infected aren't a problem for the first two maps of Dead Center, then they shouldn't be a problem for the last two maps.

If you would like to test how it would work for yourself, I made a steam workshop addon to show it off: "https://steamcommunity.com/sharedfiles/filedetails/?id=2398413726"

**Comment by CubaOfficial** [comment]
The evacuation center is abandoned, so why would CEDA still be there? Nick even has lines about CEDA leaving them. Sure you could say they are strangers that got left behind and got infected, but that's just semantics.

**Comment by True-Boredom** [comment]
> The evacuation center is abandoned, so why would CEDA still be there? Nick even has lines about CEDA leaving them. Sure you could say they are stragglers that got left behind and got infected, but that's just semantics.

Why are there zombies in the mall if they were not evacuees? If there is a way for zombies off the street to get in the building, why are there not also hazmat infected? The streets are filled with ceda agents, but the official evac center at the mall is barren? (Not to mention, it is already planned to add hazmat infected to specific parts of c1m3 in in the next community update, so why not add them to the rest of the map to be consistent with c1m1 and c1m2?) I mean, come on? The evac at the hotel was ALSO abandoned and all the ceda agents inside and outside the building are stragglers, but NO we can't have ceda agents INSIDE the big mall evac center! That's ridiculous! That is why we should remove the hazmat guys from inside Mercy Hospital -- the only ceda agents will be in the streets, where they belong! (Funnily enough, that's actually how it was pre-TLS)

**Comment by CubaOfficial** [comment]
Not sure why you got so worked up about that. CEDA is implied to have just up and left the people inside to die, staff on the streets are most likely the unlucky few that got bit. You can twist the scenario many ways if you try hard enough. I really don't think this is something that needs to be in the game as official content. You have made a mod to cater to those who it bothers but this is just change for changes sake.

**Comment by RiseMods** [comment]
idk why they're in the construction site but not on the actual finale (never made sense to me) i think they should only be in the hospital, but as for the mall it wouldn't make sense that they are roaming the entire mall as they were only setup near the finale of the mall

**Comment by CubaOfficial** [comment]
I can agree on most of Rise's statements wholeheartedly, but aside whatever reason you have to make up for why they is CEDA in the mall, what makes this something that needs to be in the game and cannot be a mod? Again, for those that it bothers they can use your mod, everybody wins that way.

**Comment by Tsuey** [comment]
Hey, we don't have any plans to make this population alteration for the time being.

Thanks for the suggestion, though I think there's clearly a split on this suggestion in particular so it's time to close this out.
