### ISSUE TITLE
Forcing versus mode on server cause issues

### ISSUE THREAD

**Issue by lunatixxx** [Tsuey/L4D2-Community-Update#240]
mp_gamemode cause issues and connecting directly with ip keep some values of survival mode (i'm not talking about official servers as you can't force a gamemode this way but of custom servers). For example only one side played in VS, broken spawn distance of SI, anormally long stumble for SI... 
it does not happen on some competitive servers because they are using confogl which load a custom gamemode with the help of the "changelevel" plugin that change map correctly without bugs.

**Comment by lunatixxx** [comment]
Workaround is to create a plugin that call a vote and reload the map  but is not very convenient (smilar to the vote of confogl):
sm_cvar mp_gamemode versus
sm_changelevel "map"

**Comment by Treescrub** [comment]
A fix isn't feasible for changing mp_gamemode during a game without restarting.
