### ISSUE TITLE
Survivors standing/coughing in Smoker's smoke cloud should aggro nearby common infected

### ISSUE THREAD

**Issue by True-Boredom** [Tsuey/L4D2-Community-Update#242]
In TLS, oxygen tanks were made useful by allowing the hissing sound they make to draw common infected toward them. I think it would be a cool idea for the smoke cloud of a deceased Smoker to work the same: when a survivor stands in the smoke, their character coughs, and this could draw nearby commons toward them (as long as no survivor is boomed, whichi should have priority).

**Comment by alexiscoutinho** [comment]
I think your suggestion is more suitable for a mod. It wouldn't make sense for the Survivor's coughs to draw Infected but their voices and loud weapon sounds not. The Smoker cloud is not an item to deserve such special status and love. It is already useful to the Infected by blocking vision. It would also throw off the balance as a Survivor in the smoke is already more vulnerable.

**Comment by Nesciuse** [comment]
It would made more sense for them to enter their aware state or whatever it’s called. Maybe they already do so not sure now. Straight up running to you wouldn’t be such a bad thing either though from gameplay perspective
