### ISSUE TITLE
Tank still spawns early in versus c1m1

### ISSUE THREAD

**Issue by Jturner2223** [Tsuey/L4D2-Community-Update#269]
This is an infamous bug that hasn't been fixed in years. Moving the tank spawn up to a point where the survivors would have to leave the elevator and open the doors would easily fix this.

**Comment by Tsuey** [comment]
Yeah, we'll have a fix for this next time we're part of an official update. No ETA on that yet, though.

**Comment by Treescrub** [comment]
@Tsuey Is this resolved?

**Comment by Tsuey** [comment]
I'd certainly hope so :hollynana:

Fixed most likely with https://github.com/L4D-Community-Team/Last-Stand-Refresh
