### ISSUE TITLE
Water Slowdown Suggestion

### ISSUE THREAD

**Issue by True-Boredom** [Tsuey/L4D2-Community-Update#272]
In Campaign mode, stepping in ankle-deep water slows you down to 115 HU, from 220 (almost 50%) -- this feature hurts the popularity of Swamp Fever and Hard Rain, two campaigns that heavily feature water slowdown.

However, in Versus mode, the slowdown is only 170 HU which makes it much less annoying to tredge water. What I suggest is that all gamemodes should have the reduced water slowdown as Versus mode, or only deeper bodies of water should give the full slowdown.

**Comment by alexiscoutinho** [comment]
I think the water slowdown values in coop should aim to be **realistic**, even if it is inevitably annoying (that's the charm/uniqueness of these campaigns), and not necessarily follow Versus. I don't know how bad the current values are, so I'm not against tweaking them.
