### ISSUE TITLE
Change time of day for c3m4

### ISSUE THREAD

**Issue by True-Boredom** [Tsuey/L4D2-Community-Update#278]
### Suggestion

The time of day for c3m4 is the considered "night", which means witches will sit instead of wander around, even though the sun is out. Witches cannot spawn on this map in campaign mode, but they can in versus mode -- often spawning to the side of the main path, near the tractor, sitting in the grass where they are hard to see.

TLDR: I suggest changing the time of day of c3m4 to "Afternoon" so witches will behave better when they spawn on this map.

**Comment by True-Boredom** [comment]
Found a way to get wandering witches to work on this map, by adding the following to anv_mapfixes:

*EntFire( "worldspawn", "AddOutput", "timeofday 3" );*

**Comment by alexiscoutinho** [comment]
> Edit: Unfortunately, doing it this way makes the witches walk in the l4d1 mutations

Just check the gamemode before ent firing...

**Comment by True-Boredom** [comment]
> Just check the gamemode before ent firing...

You're right, this fixes it:
`EntFire( "worldspawn", "AddOutput", "timeofday 3" );
if ( g_MutaMode == "l4d1coop" || g_MutaMode == "l4d1vs" )
{
	EntFire( "worldspawn", "AddOutput", "timeofday 0" );
}`

**Comment by JuggerLeft** [comment]
I think that they kept it as a Dark Level as a method of balance because of the Double Tank at the end, you can take a lot of damage until you get to them, i think that it could be changed to daytime on versus though to make it more intense since there's no Double Tank on Versus

**Comment by True-Boredom** [comment]
While changing the time of day might "make sense", the gameplay benefits of having the map be considered night outweigh this, especially since not all players might like the change.
