### ISSUE TITLE
z_smoker_limit overidde in custom maps

### ISSUE THREAD

**Issue by lunatixxx** [Tsuey/L4D2-Community-Update#294]
### Description

Some custom campaigns still have the priority on the cvar "z_smoker_limit" and can decide to spawn it despite being on zero, it seems to only happen with smoker from what i see.

City 17 v3.2 _map 2_, crash bandicoot remaster _map 2_ notably. (versus)

**Comment by True-Boredom** [comment]
Are you sure this is a bug and not a script file being activated? Some official campaigns utilize scripts to increase/decrease special infected limts. For example, on Dark Carnival after you leave the motel and are about to jump down the large sloping hill, a script file named "c2_highway_ambush" activates and increases the smoker limit to 3. Dead Center's mall crescendo event also infamously increases the charger limit to 3.

**Comment by lunatixxx** [comment]
If there is one in city17 i did not find it with gfscape.

**Comment by Derpduck** [comment]
City17 map 2 runs the `c2m4_barns_onslaught2` script for its event (the same script used for Dark Carnival map 4), which changes the limits for special infected.

Can you provide more detail on your use case (in this report and future reports), it is difficult to investigate issues if no details on modifications are given.

Are these AI smokers spawning, or are they being given to players?

**Comment by lunatixxx** [comment]
On city17 map 2 i disabled all infecteds bots with cvar except hunters for 2vs2 match. There were no players just me and indeed the cvar was not respected all infected bots were spawning charger spitter ect. 
When i used director_allow_infected_bots 0 it was respected and bots did not spawn.

Crash bandcioot map 2 even with director_allow_infected_bots 0 the same smoker bot spawn always at the same place.

So yes scripts like you said. But how did you find out that it was using c2m4_barns_onslaught i can't find it in vpk?

**Comment by Derpduck** [comment]
This is not a bug, this is completely normal behaviour. If your versus game is not full, then infected AI will spawn. If you wish to change this behaviour there are already existing tools to do so.

The Crash Bandicoot map uses an `commentary_zombie_spawner` entity to spawn infected manually, which will bypass any director limits. This is not a bug and not uncommon in some custom maps.

BSPSource can be used to decompile maps, which is how I checked the script.
