### ISSUE TITLE
c5m1 _skybox_shielda does not block both sides

### ISSUE THREAD

**Issue by Derpduck** [Tsuey/L4D2-Community-Update#3]
This clip on a roof on c5m1 to block a stuck spot on the skybox doesn't extend all the way to the other side, meaning it's still possible to get stuck here.

Seems to be caused by using a negative value in the maxs.

https://github.com/Tsuey/L4D2-Community-Update/blob/be0cf3b251627fe018916c3670cc60eeee81db31/scripts/vscripts/anv_mapfixes.nut#L1578

![](https://i.imgur.com/0IJcfjh.jpeg)

**Comment by Derpduck** [comment]
Here's some values I've come up with to fix this
```
"origin" "-384 -2054 108"
"mins" "-64 -6 -36"
"maxs" "64 6 36"
```
![](https://i.imgur.com/wVfsr6F.jpg)

**Comment by Tsuey** [comment]
Sick, thanks! Fixed in the next commit.
