### ISSUE TITLE
Add Director.AreAllSurvivorsInBattlefieldArea()

### ISSUE THREAD

**Issue by alexiscoutinho** [Tsuey/L4D2-Community-Update#310]
### Suggestion

This would be just as useful as `Director.AreAllSurvivorsInFinaleArea()`.

**Comment by A1mDev** [comment]
I think it is possible to recreate this function with vscripts, judging by the code this is not a very accurate function, if i am not mistaken it does not count all the survivors, it just skips them if they are dead or incapacitated, so you can make the code better and more accurate with vscripts. Well, except that the vscripts system itself is slower. It's just a loop through the players with a navarea check:

```
signed int __cdecl ForEachTerrorPlayer<SurvivorsInFinaleScan>(_BYTE *a1)
{
	int v1; // ebx
	CBaseEntity *v2; // eax
	CBaseEntity *v3; // esi
	int v4; // eax
	int v6; // eax

	v1 = 1;
	if ( gpGlobals->maxClients <= 0 )
		return 1;
	while ( 1 )
	{
		while ( 1 )
		{
			v2 = (CBaseEntity *)UTIL_PlayerByIndex(v1);
			v3 = v2;
			if ( v2 )
			{
				v4 = *((_DWORD *)v2 + 12);
				if ( v4 )
					break;
			}
LABEL_6:
			if ( gpGlobals->maxClients < ++v1 )
				return 1;
		}
		if ( (v4 - LODWORD(gpGlobals[1].interval_per_tick)) >> 4 )
			break;
		if ( gpGlobals->maxClients < ++v1 )
			return 1;
	}

	if ( !v3->IsPlayer()
		|| player->IsConnected()
		|| !v3->IsAlive()
		|| v3->GetTeamNumber(v3) != 2
		|| !a1[1] && v3->IsIncapacitated() )
	{
		goto LABEL_6;
	}

	*a1 = 0;

	TerrorNavArea pNavArea = v3->GetLastKnownArea();
	if ( pNavArea )
	{
		if (pNavArea->GetSpawnAttributes() & NAV_SPAWN_FINALE)
		{
			goto LABEL_6;
		}
	}

	return 0;
}
```

**Comment by alexiscoutinho** [comment]
Lol, then they forgot to hook it up in `Director.`...

**Comment by alexiscoutinho** [comment]
Added in [2.2.2.8](https://steamcommunity.com/games/L4D2/announcements/detail/3646280012042428637).
