### ISSUE TITLE
Reverting the Cvar value changes to the Glow System.

### ISSUE THREAD

**Issue by SherlockHolmes9** [Tsuey/L4D2-Community-Update#332]
### Suggestion

Previously the CVAR value for glow RGBA is from 0-255. This enable us to have multiple rainbow of color to use.

But since the new CVAR value system to glow value we can't have the black color now. Set all RGB to 0 mean the color turn off. 

This is quite a problem since i like having dark red or dark blue.

Valve, pls fix.

**Comment by Derpduck** [comment]
I don't believe the glow cvars were changed at all, could you provide more information please?
Can you post which cvars you are specifically having issues with?
And just to note for clarity, the glow cvars have always used values between 0 - 1, not 0 - 255.

**Comment by Treescrub** [comment]
I tested this on an old version (2.0.4.5) and the latest version (2.2.2.6), and the behavior appears to be identical.
From some testing with the glows, the opacity/size of the outline seems to be determined by the "length" of the RGB vector. Adding cvars to also control glow alpha would probably be a reasonable way to allow dark color glows.
