### ISSUE TITLE
Updated mutation .nut script files from 10 months ago are broken

### ISSUE THREAD

**Issue by Mysterious-Pootis** [Tsuey/L4D2-Community-Update#335]
### Description

I think updated mutation .nut script files from 10 months ago have the wrong code. For example instead of DirectorOptions it has MutationOptions which doesn't work.

### Reproduction steps

Loading up Tank Run with the .nut file from this github and seeing the game not activating the code, spawning commons and not spawning tanks.

**Comment by alexiscoutinho** [comment]
Using `MutationOptions` is the recommended way to initialize Director options in mutations. You must be loading the updated scripts incorrectly. You can test the files from the [Candidate 10-3-2021](https://github.com/Tsuey/L4D2-Community-Update/releases/tag/v1.1.2) release using the [TLS Community Update Testing Initiative](https://steamcommunity.com/sharedfiles/filedetails/1959405608) addon.
