### ISSUE TITLE
the game crashed when I picked up other melee weapons

### ISSUE THREAD

**Issue by ICRabbits** [Tsuey/L4D2-Community-Update#380]
### Description

When I picked up other melee weapons, no matter the katana, axe, or other melee weapons, the game may crash and quit with a high probability (up to 80%) and without any error report but generates dump files in the game folders, no matter add mods or not.
I have tried many methods to solve this problem, such as verifying the game files, deleting or disabling melee weapons mods, and reinstalling the game, but all don't work.
Please help me to fix it. This has been bothering me.

### Reproduction steps

Loading an arbitrary map
pick up a melee weapon
80% probability the game will be crashed;

When the game crashes, the console will show these messages (extracted from the console.log)
Infinite origin from vphysics! (entity weapon_melee)
Infinite angles from vphysics! (entity weapon_melee)
Infinite origin from vphysics! (entity weapon_melee)
Infinite angles from vphysics! (entity weapon_melee)
Infinite origin from vphysics! (entity weapon_melee)
Infinite angles from vphysics! (entity weapon_melee)
Infinite origin from vphysics! (entity weapon_melee)
Infinite angles from vphysics! (entity weapon_melee)
Infinite origin from vphysics! (entity weapon_melee)

### Additional files

[left4dead2_crash_20230624004846_1.zip](https://github.com/Tsuey/L4D2-Community-Update/files/11850792/left4dead2_crash_20230624004846_1.zip)
![微信图片_20230624012219](https://github.com/Tsuey/L4D2-Community-Update/assets/137529641/9621fd92-56a7-4d2e-b7a9-dec206d95d5b)
[console.log](https://github.com/Tsuey/L4D2-Community-Update/files/11850800/console.log)

**Comment by Treescrub** [comment]
Have you tested with **all** mods disabled?

**Comment by ICRabbits** [comment]
> Have you tested with **all** mods disabled?
No, I only removed the melee weapon mods, but at the very beginning, I only removed some melee weapon mods that included scripts that may cause this issue. However, it still occurs. 
As you know, playing this game nowadays without mods is boring. Other mods, such as UI and gun mods, have been installed for a long time( maybe for many years), and I don't think they will cause this issue, although I'm not sure.
However, I still want to figure out what causes this issue. The console does not point out what happened clearly, and maybe the dump files could show what happened, but I cannot open and read it.

**Comment by ICRabbits** [comment]
> Have you tested with **all** mods disabled?

https://steamcommunity.com/app/550/discussions/0/3808404524160819212
_Only picking up other melee weapons may occur this issue. Even if I pick up a concealed weapon, which is a knife of CSS, not modded, it still crashes._

**Comment by Treescrub** [comment]
You should still try disabling all mods and seeing if it still occurs. Mods need to be ruled out because they are the most common cause of issues. Even if you _think_ the mods aren't causing it, taking a little bit of time to verify that it isn't the mods will be very helpful.

**Comment by Treescrub** [comment]
Assuming it was caused by a mod due to no response.
