### ISSUE TITLE
Special Colored Infected

### ISSUE THREAD

**Issue by lDrDooml** [Tsuey/L4D2-Community-Update#393]
### Question

Hi, I wanted to ask if there are any plans to introduce soon the possibility of being able to color all the special infected, if I remember correctly there was a video related to the progress made for the game some time ago where it was shown that you could color infected such as the boomer (male), hunter, charger and smoker that to this day cannot be colored.

It would be quite good for both custom maps and people who use a plugin to change the color.
![especiales_colores2](https://github.com/Tsuey/L4D2-Community-Update/assets/92607636/582be075-c391-40f4-a03b-a3fc347edbd8)

**Comment by Tsuey** [comment]
Yeah, that has been [implemented](https://github.com/Tsuey/L4D2-Community-Update/blob/master/changelogs/Future_Update_01.md#special-infected) for about 2 years and we hope to get it in soon!

**Comment by alexiscoutinho** [comment]
Implemented in #61.
