### ISSUE TITLE
c5m4 _commonhop_electricalbox clip

### ISSUE THREAD

**Issue by Derpduck** [Tsuey/L4D2-Community-Update#4]
https://github.com/Tsuey/L4D2-Community-Update/blob/master/scripts/vscripts/anv_mapfixes.nut#L1805

Clip is missing a negative sign on one of its min values, so it does not block survivors from standing on this clip properly.

![](https://i.imgur.com/3yLo4kK.jpg)

**Comment by Tsuey** [comment]
Will be fixed in the next commit!
