### ISSUE TITLE
Rochelle B&W friendly fire response is bugged

### ISSUE THREAD

**Issue by ChimiChamo** [Tsuey/L4D2-Community-Update#405]
### Description

The response "PlayerFriendlyFire2Producer" doesn't play in game.

It seems the issue comes from one of the criteria being "IsFriendlyFire" whereas all other friendly fire lines have "IsNotFriendlyFire"

### Reproduction steps

Ro taking friendly fire damage when black and white plays no scenes minus the pain sounds.

**Comment by alexiscoutinho** [comment]
Resolved by 87821d3979cdc4ca8e4507dbb4f33be3c20b208a.
