### ISSUE TITLE
So, this sound voice lines...

### ISSUE THREAD

**Issue by krosktv** [Tsuey/L4D2-Community-Update#417]
### Suggestion

[Jim_Legacy.zip](https://github.com/Tsuey/L4D2-Community-Update/files/12445510/Jim_Legacy.zip)

**Comment by Shadowysn** [comment]
The team doesn't accept AI voicelines.

**Comment by krosktv** [comment]
> The team doesn't accept AI voicelines.

It's no IA VL.

**Comment by krosktv** [comment]
> The team doesn't accept AI voicelines.

You can believe in whatever you want to believe, I don't care tbh "pal"

**Comment by Shadowysn** [comment]
AI voiceline quality is not good enough to sound as natural as the old voicelines. And it's not my stance, but the team's stance. Even if I support the voiceline, I can't do anything about it without everyone else knowing and stopping me.

**Comment by krosktv** [comment]
> 
I recently added and remember everything I knew years ago and those lines were saved 'cause I had told my great-grandpa to record some similar ones. He do me a favor, those have been stored for years and now, finally I can just put them in the game.

**Comment by krosktv** [comment]
> AI voiceline quality is not good enough to sound as natural as the old voicelines. And it's not my stance, but the team's stance. Even if I support the voiceline, I can't do anything about it without everyone else knowing and stopping me.

Those lines are from the year 2016, September

**Comment by alexiscoutinho** [comment]
@krosktv If they were recorded from your great-grandpa, then I think AI would help to make them match even better with the original voices (perhaps use the ones you have as input for a [model](https://www.youtube.com/watch?v=9TroP5mR3CM)). Regardless, if you want to get them in the game you can try the workshop.

**Comment by Shadowysn** [comment]
FYI Axel refers to Jim French as their great-grandpa. Not sure why, but they don't seem to be directly naming him here.

**Comment by krosktv** [comment]
> FYI Axel refers to Jim French as their great-grandpa. Not sure why, but they don't seem to be directly naming him here.

Exactly, but I love my privacy, I would hate to have "so many requests" and get asked "alot of questions" I just want his character not to be so outdated

**Comment by krosktv** [comment]
> @krosktv If they were recorded from your great-grandpa, then I think AI would help to make them match even better with the original voices (perhaps use the ones you have as input for a [model](https://www.youtube.com/watch?v=9TroP5mR3CM)). Regardless, if you want to get them in the game you can try the workshop.

I almost forgot, I like to fix details that the game does not have by default. on all maps tbh, always when I put something Tsuey or Xanaguy closes them, I still don't understand why but Kerry is the one who says "No". Well, so It's okay, but if they do it 'cause "it doesn't seem right" it's weird... they don't even bother to test it.

**Comment by krosktv** [comment]
> @krosktv If they were recorded from your great-grandpa, then I think AI would help to make them match even better with the original voices (perhaps use the ones you have as input for a [model](https://www.youtube.com/watch?v=9TroP5mR3CM)). Regardless, if you want to get them in the game you can try the workshop.

You can see it here: https://youtu.be/C6P7tuKMHmM (P. S: I made some edits that are hardly noticeable... as I messed up sometimes.)

**Comment by alexiscoutinho** [comment]
Why Spanish though? And also, why are many voice file names missing from the game? I believe Valve purposely didn't include those missing files because they didn't sound good enough or just felt, strange/out of place. Thus, if they don't want even the originals, then the only place your sounds could fit would be in a mod.

**Comment by alexiscoutinho** [comment]
I see.
