### ISSUE TITLE
L4D1 Survivors Don’t Respond To Friendly Fire With Active Tank

### ISSUE THREAD

**Issue by Trashlyn** [Tsuey/L4D2-Community-Update#419]
### Description

After the restoration of the L4D2 survivors’ Tank friendly fire lines, the L4D1 survivors stopped responding to friendly fire when there is an active tank.

### Reproduction steps

Encounter a tank on any map or mutation and unload into your teammates.

**Comment by xanaguy** [comment]
The current, on vanilla version of the game has this set to be disabled when there's a tank present (even if there's one present, but not aggro'd in coop modes). There was a recent change that narrowed this down to where a tank must be aggro'd. To go in accordance with the recent official update.

**Comment by alexiscoutinho** [comment]
@xanaguy But is there still a difference in behavior between the L4D2 and L4D1 survivors?

**Comment by alexiscoutinho** [comment]
💀
