### ISSUE TITLE
Wrong line in PlayerReviveParishProducerCoach

### ISSUE THREAD

**Issue by MisterMayoNL** [Tsuey/L4D2-Community-Update#437]
### Description

The first possible voiceline in the response is:

	scene "scenes/Coach/WorldC5M5B21.vcd"  //We are too close. I am NOT gonna let you die here.

This is in reality the wrong line, WorldC5M5B22 is the correct line with the captions above.
The current line instead says in-game:
"Man, you (are) too close. We are NOT gonna die here."

**Comment by Voxatious** [comment]
Man I tried telling xana this a while ago but he just dismissed it thinking it was only a problem with the comment
This is what he said 
"- Not a talker change. The texts after // are commented out and serve no function other than identifying which lines are which."
