### ISSUE TITLE
Nick's PlayerWitchChasing response using non-existant scenes

### ISSUE THREAD

**Issue by ChimiChamo** [Tsuey/L4D2-Community-Update#450]
### Description

The PlayerWitchChasingGambler rule includes 2 scenes that don't exist, that being "Fall01" and "Fall04". The ones that should be used are "LedgeHangFall01" and "LedgeHangFall04". If I'm honest, I don't think the lines would fit well anyway but still.

**Comment by MisterMayoNL** [comment]
I'd like to add that LedgeHangFall04 does not exist, because Fall04 is a duplicate of Fall01

**Comment by Voxatious** [comment]
> ### Description
> The PlayerWitchChasingGambler rule includes 2 scenes that don't exist, that being "Fall01" and "Fall04". The ones that should be used are "LedgeHangFall01" and "LedgeHangFall04". If I'm honest, I don't think the lines would fit well anyway but still.
> 
> ### Reproduction steps
> _No response_
> 
> ### Additional files
> _No response_

Strange, I thought I already reported this to Xana. Not sure why it hasn't been changed yet.

**Comment by xanaguy** [comment]
Fixed per commit. Closing.
