### ISSUE TITLE
Minor issue with Namvet talker script

### ISSUE THREAD

**Issue by ChimiChamo** [Tsuey/L4D2-Community-Update#458]
### Description

The response rule "SurvivorSpottedVomitJarAutoNamVet" has IsNotSaidSpotMolotov as one of the criteria instead of IsNotSaidSpotVomitJar. It seems the response was copy pasted from the molotov one above and this criteria was missed

**Comment by MisterMayoNL** [comment]
All L4D1 characters have this issue

**Comment by xanaguy** [comment]
Fixed.
