### ISSUE TITLE
Duplicate IsPickedUpcricket_bat

### ISSUE THREAD

**Issue by MisterMayoNL** [Tsuey/L4D2-Community-Update#463]
### Description

Coach & Nick both have 2 IsPickedUpcricket_bat rules & responses (SurvivorPickupcricket_bat & SurvivorPickupCricketBat). The duplicate one uses all generic TakeMelee lines.

Another mistake I found was that SurvivorSpottedAxeProducer & SurvivorSpottedFryingPanProducer have the required weapon switched. SurvivorSpottedAxeProducer has IsFryingPan and SurvivorSpottedFryingPanProducer has IsFireAxe. As these use generic weapons spotted lines it doesn't do anything, but it should still be pointed out.

**Comment by xanaguy** [comment]
Fixed per commit, Nick's version is commented out JUST in case there's a use in the future.
