### ISSUE TITLE
Game not detecting addons?

### ISSUE THREAD

**Issue by Living-Cheesestick** [Tsuey/L4D2-Community-Update#466]
### Description

I subscribed to a bunch of stuff on the workshop and it successfully downloaded, but the game doesn't detect it for some reason. I tried validating the game files, resubscribing, moving the worksop mods to the addons folder, and even uninstalling and reinstalling the game. none of it's working. Only a select few are being detected and even that's inconsistent. A select few mods get detected at first, but when I validate the files or reinstall, the game detects different mods this time. If there's a fix, I'd love to know

**Comment by Living-Cheesestick** [comment]
Never mind, one of my friends is a troll and changed my addonlist.txt to read only

**Comment by Tsuey** [comment]
Understandable, thanks for keeping us posted.
