### ISSUE TITLE
Zoey's SpottedShotgun Rules have the wrong criteria

### ISSUE THREAD

**Issue by Mysterious-Pootis** [Tsuey/L4D2-Community-Update#469]
### Description

Zoey's "SurvivorSpottedPumpShotgunAutoTeenGirl" and "SurvivorSpottedShotgun_ChromeAutoTeenGirl" Rules have IsSmg_silenced criteria. Which obviously shouldn't be there.

**Comment by xanaguy** [comment]
It seems like this repository's teengirl.txt already has this fixed.

**Comment by Mysterious-Pootis** [comment]
> It seems like this repository's teengirl.txt already has this fixed.

I just checked and the talker that is in this repository does indeed still contain incorrect criteria
![Incorrect criteria](https://github.com/Tsuey/L4D2-Community-Update/assets/104587389/889123f6-d732-4be6-ab85-0e2cdef7e9be)

**Comment by xanaguy** [comment]
Fixed. Turns out there were extra criteria for which weapon is spotted.
