### ISSUE TITLE
Missing predelays on "ReviveMeInterrupted" concept for Nick and Francis

### ISSUE THREAD

**Issue by ChimiChamo** [Tsuey/L4D2-Community-Update#471]
### Description

There is no predelay set for Nick's "ReviveMeInterruptedCritical" response and none set for Francis' "L4D1ReviveMeInterruptedMajor" and "L4D1ReviveMeInterruptedCritical" responses which doesn't fit the pattern of the other survivors

**Comment by xanaguy** [comment]
Should be fixed now/
