### ISSUE TITLE
Missing "NotPickedUpItem" criteria for Rochelle's pickup upgrade ammo responses

### ISSUE THREAD

**Issue by ChimiChamo** [Tsuey/L4D2-Community-Update#472]
### Description

Rochelle's responses for SurvivorPickupUpExplosivesProducer and SurvivorPickupUpIncendiaryProducer is missing the "NotPickedUpItem" context.

**Comment by MisterMayoNL** [comment]
SurvivorPickupExplosiveAmmoCoach also uses IsPickedUpIncendiaryAmmo isntead of IsPickedUpExplosiveAmmo

**Comment by xanaguy** [comment]
Did this for one more rule, too, but this is fixed.
