### ISSUE TITLE
Wrong followup targets for C7M3_saferoom014Biker & C7M3_saferoom014aManager

### ISSUE THREAD

**Issue by ChimiChamo** [Tsuey/L4D2-Community-Update#475]
### Description

The two responses in the title have "any" as their "then" target. However, only Louis and Francis have the concepts these are targetting, so the conversation usually won't play out.

**Comment by ChimiChamo** [comment]
Taking a further look a lot of the Sacrifice saferoom dialogue has this issue with Francis and Louis

**Comment by MisterMayoNL** [comment]
This doesn't break anything with the talker. As Francis & Louis are the only ones with a response, they will always be picked for it. The "Any" function only looks at survivors that have a response. Those that don't can't be picked

**Comment by xanaguy** [comment]
> This doesn't break anything with the talker. As Francis & Louis are the only ones with a response, they will always be picked for it. The "Any" function only looks at survivors that have a response. Those that don't cannot be picked

This is correct. Nothing is broken here.
