### ISSUE TITLE
stuck in the ground when ever I start up a campaign 

### ISSUE THREAD

**Issue by lazymagic2** [Tsuey/L4D2-Community-Update#494]
### Description

I load up a campaign in single player and I'm just stuck in the ground I've tried verify my my files uninstalling all my mods nothing works for me so far

**Comment by Treescrub** [comment]
Which campaigns? Also what do you mean by "stuck in the ground", are you just unable to move? Screenshots/video would be helpful if you have any.

**Comment by lazymagic2** [comment]
![image_2024-03-26_193626513](https://github.com/Tsuey/L4D2-Community-Update/assets/164712054/8d6643f3-e691-4c90-b44b-3eaaac45e4fe)

**Comment by lazymagic2** [comment]
it's all the campaigns and i can't move shoot or just do anything really

**Comment by lazymagic2** [comment]
Uploading Untitled video - Made with Clipchamp.mp4…

**Comment by Tsuey** [comment]
Do you have a game controller plugged in? Try unplugging it?

**Comment by Treescrub** [comment]
If you go into the options, go to `Keyboard/Mouse`, and `Edit Keys/Buttons`, does it show any keys on the right side?

**Comment by lazymagic2** [comment]
ok yeah it was the controls but I never touch the also thank you I'm going to delete the post
