### ISSUE TITLE
Since the Community Update, Left 4 Dead 2 will not open.

### ISSUE THREAD

**Issue by Handful-of-Sand** [Tsuey/L4D2-Community-Update#51]
Going to paste here what I've submitted to the Community Discussion page on Steam: 

Since the recent update, Left 4 Dead 2 will not open. I've noticed that this is extended to my other Source games as well (but specifically Portal 2). Before I continue, I've attempted to run the exe's as administrator, have run Steam as administrator, have edited launch options for the exe's according to guides online that cover the issue. I've added options to the Steam launch window (-windowed, -novid, etc)., I've verified the integrity of the game files several times. I've uninstalled and reinstalled the game (trying it on different drives each time.) I've followed youtube videos, yahoo answers guides... have added exceptions to the programs in my firewall!

I don't have a VPN running, or Afterburner (as some guides suggest is the issue), I don't have antivirus software running (beyond Windows Defender, which I've added exclusions to for my Source games). I do subscribe to several addons, but have tried the game with or without to no avail. TO MY KNOWLEDGE, all appropriate files have 'read only' switched OFF. 

My specs are as follows: (Windows 10, Ryzen 5 3600x, RTX 2060 Super, 16g/3200, 2 Sata SSD's, 1 NVME SSD, 1 HDD). I should also mention that I'm running three screens - two Display Port 144hz monitors (labeled 1/2 by Windows System Config) and a third, HDMI, 60hz TV (labeled 3). 

I bring these up because I've managed to solve my Left 4 Dead 2 issue exactly _twice_, but inconsistently. The fix was to - I'm not kidding - unplug the HDMI cable from my GPU. Whether the HDMI cable is plugged into a monitor/tv or not, simply unplugging the HDMI cable has fixed the issue *twice*, out of maybe ten attempts. That is literally the only fix I've found so far for the issue. Plugging the HDMI cable back in once the game is running isn't an issue, the game continues on just fine. But if I close the game, it will not re-open. Maybe that's a symptom of an underlying, larger issue, but short of re-imaging my computer, I'm out of ideas to fix the program. If there's any information I can provide you (within my scope of understanding I guess) I'm happy to try and help. I've got a thousand hours in the game, and had no issues running the game whatsoever until this update (but I DO see that it is a recurring issue in the past).

Edit: changed 'Whether the HDMI cable is plugged in or not...' to 'Whether the HDMI cable is plugged into a monitor/tv or not,..." for clarity

**Comment by shqke** [comment]
It might seem obvious to ask, but I don't see it explicitly mentioned anywhere.

Have you tried to do a [clean install](https://www.ubisoft.com/en-gb/help/connectivity-and-performance/article/clean-installation-of-nvidia-drivers/000063728) of latest GPU driver?

**Comment by shqke** [comment]
I'll close this one out, due to lack of response. If you think your issue is still not solved, - feel free to reopen.
