### ISSUE TITLE
Ellis quote not playing

### ISSUE THREAD

**Issue by phoenixplayz68** [Tsuey/L4D2-Community-Update#512]
### Description

![image](https://github.com/Tsuey/L4D2-Community-Update/assets/51034168/8ed59f83-6e17-45a8-913e-56ae8aeaa94f)
In here the "DLC1_C6M2_SafeRoomConv21.vcd" has a typo making the quote unused and never heard
instead should be this "DLC1_C6M2_SafeRoomConvo21.vcd"

I really love the Keith stories and I would love for this to be fixed

Also to finish the rest of his story instead of ignoring Rochelles response

### Reproduction steps

Change "DLC1_C6M2_SafeRoomConv21.vcd" in Ellis/Mechanic talker to "DLC1_C6M2_SafeRoomConvo21.vcd" so he has a response

**Comment by True-Boredom** [comment]
This appears to have already been fixed on the github.

**Comment by Nesciuse** [comment]
fixed in 4e2ecaf
