### ISSUE TITLE
Steam group servers not showing up

### ISSUE THREAD

**Issue by lDrDooml** [Tsuey/L4D2-Community-Update#513]
### Description

With the new update `2.2.3.8`, the function that is responsible for displaying and loading the servers visualization stopped working, the servers simply no longer respond to the requests coming from the client.

I hope this was simply some mistake and not intentional because if so the community servers are going to disappear for the simple fact that no one is going to want to rent an empty host.

Solutions have been offered such as the server browser function that the game offers but it does not work correctly and is not even added to the game menu, so it is a terrible solution because the vast majority of players are ignorant in this matter and connect to the first server they see.

**Comment by alexiscoutinho** [comment]
Yeah, some of my friends are also complaining about this. They can only use `openserverbrowser`.

**Comment by alexiscoutinho** [comment]
News?

**Comment by alexiscoutinho** [comment]
Fixed on 26 May 2024: https://steamcommunity.com/games/L4D2/announcements/detail/4168722935772243546.
