### ISSUE TITLE
Any server(Version 2238) cannot be displayed in the group server list and cannot handle matchmaking requset.

### ISSUE THREAD

**Issue by Localia-cn** [Tsuey/L4D2-Community-Update#518]
### Description

After [previous update](https://steamcommunity.com/app/550/eventcomments/4360125073503685563) (version 2238), the server was unable to generate the "**InetSearchServerDetails**" and "**ConnectServerDetails**" packets, and the client was also unable to process these two packets from the server. This led to the server not being able to display in the group server list[(#6007)](https://github.com/ValveSoftware/Source-1-Games/issues/6007) and unable to handle matchmaking requests.

After [today's client update](https://steamcommunity.com/app/550/eventcomments/4334230493284730597), it seems the client files have reverted, and the client is now able to process these two packets again. However, the server has not been updated, so the functionality remains broken.

Following the previous update, many dedicated server owners chose to cope with the update by simply editing the version number to 2238, while their actual file version remains at 2237, so after today's client update, these servers can now once again display in the group server list and can use the matchmaking. However, for those servers that have truly updated to version 2238, these two functions remain broken.

### Reproduction steps

1. Any server that has truly upgraded to version 2238 will not be displayed in the group server list.
2. Connecting to any **empty** official server from openserverbrowser will prompt "Connection failed after 10 retries." (because the server cannot respond to the "ConnectServerDetailsRequest" packet from the client).

**Comment by oethanx** [comment]
This issue still persist. Custom servers do not show in the main menu for players despite it being set with sv_steamgroup. Although, for some unknown reason, there are some Chinese server showing up in the main menu

**Comment by A1mDev** [comment]
Because these servers remained on the old build

**Comment by pa4H** [comment]
The problem is very urgent. Please fix it as soon as possible!

**Comment by jhargis** [comment]
What are you doing?  It's broken.  ROLLBACK and deploy.  It's been over a week, this is absurd.

**Comment by oethanx** [comment]
I'm sure it's not that time consuming to rollback a simple bug

**Comment by alexiscoutinho** [comment]
Valve time. Gotta be patient.

**Comment by A1mDev** [comment]
Fixed

**Comment by alexiscoutinho** [comment]
Presumably in [2.2.3.9](https://steamcommunity.com/games/L4D2/announcements/detail/4185612701673745272).
