### ISSUE TITLE
Better feedback messages on disconnects

### ISSUE THREAD

**Issue by FurtadoPires** [Tsuey/L4D2-Community-Update#82]
You all are probably aware of this one

After some recent small patches made the game doesn't tell the reason we were disconnected, just displaying a generic  "Client Disconnected." message.
![20211002173101_1](https://user-images.githubusercontent.com/7890832/135731233-a639d069-bafb-4841-9f45-68a03f4113de.jpg)

In this case for example was caused by a vote kick.

Would be better to have a more refined feedback like 
-"Kicked in the vote initiated by <userid>"  : Displaying who started the vote in the message
-"Kicked by the host console"  : In case of the host typing kick <userid> in the server console
-"User host disconnected" : In case of the server host quit

Or at least return with the old feedbacks instead of this one.

**Comment by JeffMakesGames** [comment]
I know that trolls that I banned get that message when trying to connect to my server.  One thing that does need fixed is a message telling when someone is joining a game.

**Comment by FurtadoPires** [comment]
> I know that trolls that I banned get that message when trying to connect to my server. One thing that does need fixed is a message telling when someone is joining a game.

"Failed to join the game because someone inside blocked you" or "Failed to join the game because you're banned from this server" would be perfect, but I don't think they can / will implement something like this

**Comment by shqke** [comment]
There was a similar fix for TF2 recently, so it makes think that change was intentional.

Still awaiting confirmation from Valve about this.

**Comment by JeffMakesGames** [comment]
> 
> 
> > I know that trolls that I banned get that message when trying to connect to my server. One thing that does need fixed is a message telling when someone is joining a game.
> 
> "Failed to join the game because someone inside blocked you" or "Failed to join the game because you're banned from this server" would be perfect, but I don't think they can / will implement something like this

Well that, but I also mean an actual JOIN message. (L4D2 doesn't do this anymore.  Sometimes it doesn't even mention someone leaving the game either.
)
Because I could be playing a public game with bots and wouldn't notice someone had joined the game til I look at the bottom of the screen.

**Comment by shqke** [comment]
```
- Fixed some incorrect disconnect messages.
```

🎉
