### ISSUE TITLE
Usage of nav_compare.nut is not clear

### ISSUE THREAD

**Issue by alexiscoutinho** [Tsuey/L4D2-Community-Update#85]
I followed the steps in the README, but saw no highlighting. I tried to compare `c8m5_rooftop.nav` and even created a new area with connections in the saferoom in the second file. Nothing changed, with and without `nav_edit 1`, and I was looking at the right place. I tried performing the second `script_execute` near and far from the changed region, nothing. The only thing I saw were the many console messages from the script and `nav_load`. Are there other conditions that must be met? I was using `-dev`, everything was done without reloading map and the rest was normal game.

**Comment by Nesciuse** [comment]
Wasn't aware the nav_compare.nut is already here. Just forget about that messy script. Uploaded a new one you can try.
