### ISSUE TITLE
"Infinite" Smoker tongue

### ISSUE THREAD

**Issue by alexiscoutinho** [Tsuey/L4D2-Community-Update#91]
Well, let a Smoker fire at you, then fly back with `noclip` (or get a crazy boost, like GL boost) and let it chase you for as long as you can.

**Comment by shqke** [comment]
Very unlikely something like this would happen in a live base game.

**Comment by A1mDev** [comment]
If i understood the problem correctly. Sometimes a tank will hit you and you fly away a long distance, then a smoker can still take a victim a very long distance or, for example, when you jump from a large ledge or when you are hit by a charger with another player, the same situation occurs.

**Comment by alexiscoutinho** [comment]
Haven't thought of those cases. Might look scuffed there too.
