### ISSUE TITLE
The Sacrifice - Rebirth (L4D2)

### ISSUE THREAD

**Issue by WiEz0170** [Tsuey/L4D2-Community-Update#95]
To be honest, you can actually alter this and be able to save the one you are trying to sacrifice.

I have seen the whole map and I had wondered why there are some things that can be modified, that in most maps cannot be done.

That's why I decided to change the end of the map a bit, here is a sample of the change "not yet finished"

• https://user-images.githubusercontent.com/91793676/135963606-c0fbadd2-5270-4006-bfa3-0da4e7e83827.mp4

**Comment by shqke** [comment]
Campaign outcome is not going to get altered, it is so by the canon.

Consider making a workshop addon instead. 😃

**Comment by WiEz0170** [comment]
> I think this is out of the scope of this repository, no update is going to be officially made to the game that completely changes the ending story or gameplay of The Sacrifice.

Okay, but you know that finale "official" socks right?
it is only to fall to the ground and that's it.
