### ISSUE TITLE
crashing on finales

### ISSUE THREAD

**Issue by FighterJet16** [Tsuey/L4D2-Community-Update#97]
so basically i'll be playing normally about to reach the 2nd tank I kill it and then I'm running to helicopter and then it'll crash or running to the helicopter from across the map about to make it game crash

**Comment by shqke** [comment]
Please specify following:
- map name
- game mode
- OS type
- workshop addons list
- server side mods list

Also you need to provide with corresponding `left4dead2_crash_*.mdmp` file (on windows you can find them in game folder).
